version: '3'

services:

  # Proxies requests to internal services
  dc-reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy_demo
    depends_on:
        - dc-front-end
        - dc-back-end
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5004:80

  # generates weather reports
  dc-front-end:
    image: ghcr.io/adamsolkar/dc-front-end
    container_name: dc-front-end
    build:
      context: ./composevue
    depends_on:
        - dc-back-end
    ports:
      - 8080:80
    restart: on-failure


  # Retrieves the temperature
  dc-back-end:
    image: ghcr.io/adamsolkar/dc-back-end
    container_name: dc-back-end
    build:
      context: ./BackendApi
    ports:
      - 5001:5001
    restart: on-failure
   # expose:
   #   - "5001"
   # environment:
   #   - ASPNETCORE_URLS=http://+:5001


