name: Docker2

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This is a basic workflow to help you get started with Actions


# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Print Working Directory 1
        run: pwd
      - name: List Files 1
        run: ls
###########################################
      - name: Push to DO
        run: |
          echo "$user" $user
          echo "$target_ip" $target_ip
          echo "$ssh_key" > ~/ssh_key
          shell: bash
          chmod 600 ~/ssh_key
          rsync -e "ssh -i ~/ssh_key -o StrictHostKeyChecking=no" -avzr ./docker-compose.yml "$user"@"$target_ip":/var/www/cicdtest
          rsync -e "ssh -i ~/ssh_key -o StrictHostKeyChecking=no" -avzr ./reverse_proxy "$user"@"$target_ip":/var/www/cicdtest
        env:
          ssh_key: ${{ secrets.CICD_SSH }}
          user: ${{ secrets.CICD_USER }}
          target_ip: ${{ secrets.SERVER_IP }}
          #folder_name: ${{ steps.vars.outputs.folder_name }}
###########################################



