name: Docker3

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This is a basic workflow to help you get started with Actions


on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ master ]

#on:
#  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@f3c664df7af409cb4873aa5068053ba9d61a57b6 #v2.6.0
        with:
          cosign-release: 'v1.11.0'


      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      #- name: Build and push Docker image
      #  id: build-and-push
      #  uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
      #  with:
      #    context: .
      #    push: ${{ github.event_name != 'pull_request' }}
      #    tags: ${{ steps.meta.outputs.tags }}
      #    labels: ${{ steps.meta.outputs.labels }}
      #    cache-from: type=gha
      #    cache-to: type=gha,mode=max
      
      #trying compose
      - name: Build image
        run: docker compose build
        
      #trying compose
      - name: Push image
        run: docker compose push
###########################################

      - name: Print Working Directory 1
        run: pwd
      - name: List Files 1
        run: ls
###########################################
      - name: Push to DO
        run: |
          echo "$ssh_key" > ~/ssh_key
          chmod 600 ~/ssh_key
          rsync -e "ssh -i ~/ssh_key -o StrictHostKeyChecking=no" -avzr ./docker-compose.yml "$user"@"$target_ip":/var/www/cicdtest
          rsync -e "ssh -i ~/ssh_key -o StrictHostKeyChecking=no" -avzr ./reverse_proxy "$user"@"$target_ip":/var/www/cicdtest
        env:
          ssh_key: ${{ secrets.CICD_SSH }}
          user: ${{ secrets.CICD_USER }}
          target_ip: ${{ secrets.SERVER_IP }}
          #folder_name: ${{ steps.vars.outputs.folder_name }}
###########################################
#export CR_PAT=${{ secrets.GHCR_TOKEN }}
#echo $CR_PAT | docker login ghcr.io -u adamsolkar --password-stdin
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.CICD_USER }}
          key: ${{ secrets.CICD_SSH }}
          script: |
            cd /var/www/cicdtest
            ls -a
            docker --version
            docker-compose pull
            docker-compose down
            docker-compose up -d



